const femaleNames = ["AGUIRRE, Marielle Mae Baran",
    "BACLEA-AN, Gelai Cuesta", 
    "CAS, Ma. Kristina Limosnero", 
    "CONCEPCION, Jacey Erin Dael", 
    "DE JUAN, Angela Marie Gatdula", 
    "DE LARA, Althea Mariell Calderon", 
    "DELA CRUZ, Precious Nicole Javines", 
    "ESCANILLA, Joanna Ashley Arevalo", 
    "ILANO, Victoria Yuki Mori", 
    "KADOI, Amalia Sefrioto", 
    "NONOD, Abegail Estorninos", 
    "PINEDA, Princess Mikee Oliva", 
    "PIQUERO, Paula Bianca Antig", 
    "RIVERA, Chloie Nicole Laureles", 
    "SALINAS, Nykesha Dela Cruz", 
    "TALAMOR, Shella Mandar", 
    "TANYAG, Jasmin Lorchano", 
    "VALDERAMA, Samantha Angel Eda", 
    "VILLARITO, Aira Elbanbuena"];
const maleNames = ["ADLAWAN, Justin Cholo Pomida", 
    "AGUSTIN, Ace Francis Valeriano", 
    "BARRAMEDA, Dwayne Cañete", 
    "BAYLAN, Alexander Nykko Gomez", 
    "BIAS, Max Austine Baligasa", 
    "CARTAGENA, Aaron", 
    "CLARO, Kirby Christian Coronel", 
    "COMIA, Mark Lester Bordador", 
    "CORA, Jian Christian Miguel", 
    "DE DIOS, Daren James Acosta", 
    "DELA CRUZ, Marwilson Tan", 
    "DOMALAON, John Deniel Cruz", 
    "FERNANDO, Fernando Luis Ramos", 
    "GELI, Jasper Mathieu Nocete", 
    "LARGA, Jann Earl Matthew Sombilon", 
    "LAYSON, Adrian Capuno", 
    "MAAÑO, Vince Anthony Nacario", 
    "MENDEZ, Mark Joseph Reyes", 
    "NINOLLA, John Lenon Inosanto", 
    "OBATAY, Gabriel Josh Alba", 
    "OCAMPO, Jacin Kurt Salvador", 
    "PAZ, Gabriel John Mikhael Hernandez", 
    "PEDRIGAL, Francisco Moreno", 
    "PON-AN, Carlos Alberto Isidoro", 
    "ROGADO, Gerald Tan", 
    "ROMERO, Karl Tristan Fernandez", 
    "SANARES, Jaden Salac", 
    "SOGUILON, Kelvin Vicente", 
    "SOLOMON, Justin Royse Liquigan", 
    "TAN, Kinn Iago Racaza", 
    "TUBOG, Kyrie Eleison Quiliope", 
    "VASQUEZ, John Carlo Rances"];

// Sa iyong student_database.js
const allStudents = [
    ...femaleNames.map(name => ({ name: name, gender: 'Female' })),
    ...maleNames.map(name => ({ name: name, gender: 'Male' }))
].sort((a, b) => a.name.localeCompare(b.name)); // Naka-sort na rin by name